/**
 * Frozen contract fixtures for the catalog optimization shell.
 *
 * Typed against `@repo/api-contracts` (catalog_proposal_projection.v2) so the
 * compiler enforces conformance. Fixture-only: no backend/provider calls, no
 * TinyBase persistence. The three proposals deliberately exercise the full
 * decision surface: a deferred + fresh merge (human must decide), an
 * already-approved but now-stale delete (apply blocked on drift), and a rename
 * whose council evidence expired (must recompute).
 */
import type {
  CatalogCandidate,
  CatalogEpoch,
  CatalogProposalContract,
  CouncilEvidence,
  DocumentId,
  Sha256Digest,
} from "@repo/api-contracts";

const hash = (seed: string): Sha256Digest => {
  const base = `${seed.replace(/[^a-f0-9]/g, "")}00000000`.slice(0, 8);
  return base.repeat(8) as Sha256Digest;
};
const doc = (n: number): DocumentId => n as DocumentId;
const docs = (ns: readonly number[]): DocumentId[] => ns.map(doc);

/** Local display labels for catalog entity ids (presentation bridge, not an API shape). */
export const catalogEntityNames: Readonly<Record<number, string>> = {
  11: "Invoice",
  12: "Utilities",
  17: "Invoices",
  19: "Utility",
  40: "Zzz-import-2019",
};

// --- epochs -------------------------------------------------------------------
export const catalogEpochs: readonly CatalogEpoch[] = [
  {
    epochId: "cat_epoch_7Ab3cD",
    state: "proposed",
    scope: ["tag"],
    paperlessCatalogHash: hash("ca7a1091"),
    createdAt: "2026-07-22T08:00:00Z",
    updatedAt: "2026-07-22T09:05:00Z",
    completedAt: null,
    retryCount: 0,
    candidateCount: 3,
    evidenceCount: 9,
    proposalCount: 3,
  },
  {
    epochId: "cat_epoch_5Kd8fG",
    state: "council_review",
    scope: ["tag", "correspondent"],
    paperlessCatalogHash: hash("ca7b2092"),
    createdAt: "2026-07-22T09:20:00Z",
    updatedAt: "2026-07-22T09:44:00Z",
    completedAt: null,
    retryCount: 0,
    candidateCount: 5,
    evidenceCount: 6,
    proposalCount: 0,
  },
  {
    epochId: "cat_epoch_1Ce4bJ",
    state: "applied",
    scope: ["document_type"],
    paperlessCatalogHash: hash("ca7c3093"),
    createdAt: "2026-07-21T14:00:00Z",
    updatedAt: "2026-07-21T14:38:00Z",
    completedAt: "2026-07-21T14:38:00Z",
    retryCount: 0,
    candidateCount: 2,
    evidenceCount: 6,
    proposalCount: 1,
  },
];

export const activeEpochId = "cat_epoch_7Ab3cD";

// --- candidates ---------------------------------------------------------------
export const catalogCandidates: readonly CatalogCandidate[] = [
  {
    candidateId: "cand_mergeInvoice",
    epochId: "cat_epoch_7Ab3cD",
    kind: "tag",
    intendedAction: "merge",
    x: {
      entityId: 17,
      name: "Invoices",
      nameHash: hash("17aa17aa"),
      receiptCount: 214,
      documentIdsHash: hash("d017d017"),
    },
    y: {
      entityId: 11,
      name: "Invoice",
      nameHash: hash("11bb11bb"),
      receiptCount: 1893,
      documentIdsHash: hash("d011d011"),
    },
    proposedValue: "Invoice",
    expectedEvidenceFingerprint: hash("ev17ev17"),
    expectedProposalFingerprint: hash("pr17pr17"),
    preconditions: [{ kind: "catalog_epoch", digest: hash("ca7a1091") }],
    rationale: "'Invoices' (#17) is a near-duplicate of 'Invoice' (#11) with fully overlapping usage.",
    createdAt: "2026-07-22T08:41:00Z",
  },
  {
    candidateId: "cand_deleteStale",
    epochId: "cat_epoch_7Ab3cD",
    kind: "tag",
    intendedAction: "delete",
    x: {
      entityId: 40,
      name: "Zzz-import-2019",
      nameHash: hash("40cc40cc"),
      receiptCount: 0,
      documentIdsHash: hash("d040d040"),
    },
    y: null,
    proposedValue: null,
    expectedEvidenceFingerprint: hash("ev40ev40"),
    expectedProposalFingerprint: hash("pr40pr40"),
    preconditions: [{ kind: "catalog_epoch", digest: hash("ca7a1091") }],
    rationale: "'Zzz-import-2019' (#40) has no active receipts and appears to be a stale import artifact.",
    createdAt: "2026-07-22T08:43:00Z",
  },
  {
    candidateId: "cand_renameUtilities",
    epochId: "cat_epoch_7Ab3cD",
    kind: "tag",
    intendedAction: "rename",
    x: {
      entityId: 12,
      name: "Utilities",
      nameHash: hash("12dd12dd"),
      receiptCount: 341,
      documentIdsHash: hash("d012d012"),
    },
    y: null,
    proposedValue: "Utility",
    expectedEvidenceFingerprint: hash("ev12ev12"),
    expectedProposalFingerprint: hash("pr12pr12"),
    preconditions: [{ kind: "catalog_epoch", digest: hash("ca7a1091") }],
    rationale: "'Utilities' (#12) should be singular 'Utility' to match the correspondent naming scheme.",
    createdAt: "2026-07-22T08:45:00Z",
  },
];

// --- council evidence (three reviewers per decided candidate) -----------------
export const councilEvidence: readonly CouncilEvidence[] = [
  {
    evidenceId: "evidence_curator01",
    epochId: "cat_epoch_7Ab3cD",
    candidateId: "cand_mergeInvoice",
    reviewer: "taxonomy_curator",
    evidenceDocumentIds: docs([4821, 4790, 4771, 4762, 4755]),
    inspectedDocuments: 40,
    totalDocuments: 214,
    coverage: 0.187,
    xReceiptCount: 214,
    yReceiptCount: 1893,
    xReceiptHash: hash("17aa17aa"),
    yReceiptHash: hash("11bb11bb"),
    verdict: "support",
    dissent: null,
    counterexamples: [],
    rationale: "Names are synonymous and both tag the same invoice document class; merge is safe.",
    evidenceFingerprint: hash("ev17ev17"),
    createdAt: "2026-07-22T08:52:00Z",
  },
  {
    evidenceId: "evidence_auditor01",
    epochId: "cat_epoch_7Ab3cD",
    candidateId: "cand_mergeInvoice",
    reviewer: "document_evidence_auditor",
    evidenceDocumentIds: docs([4821, 4790, 4771, 4700, 4688, 4655]),
    inspectedDocuments: 60,
    totalDocuments: 214,
    coverage: 0.28,
    xReceiptCount: 214,
    yReceiptCount: 1893,
    xReceiptHash: hash("17aa17aa"),
    yReceiptHash: hash("11bb11bb"),
    verdict: "support",
    dissent: "Two sampled documents use '#17' as a language variant; confirm locale handling before merge.",
    counterexamples: [],
    rationale: "Receipts corroborate overlap; a minority use the variant tag for non-German invoices.",
    evidenceFingerprint: hash("ev17ev17"),
    createdAt: "2026-07-22T08:58:00Z",
  },
  {
    evidenceId: "evidence_hunter01",
    epochId: "cat_epoch_7Ab3cD",
    candidateId: "cand_mergeInvoice",
    reviewer: "counterexample_hunter",
    evidenceDocumentIds: docs([4519, 4498]),
    inspectedDocuments: 30,
    totalDocuments: 214,
    coverage: 0.14,
    xReceiptCount: 214,
    yReceiptCount: 1893,
    xReceiptHash: hash("17aa17aa"),
    yReceiptHash: hash("11bb11bb"),
    verdict: "oppose",
    dissent: "Found documents where '#17' distinguishes a separate credit-note subtype.",
    counterexamples: [
      {
        documentId: doc(4519),
        rationale: "Tagged '#17' as a credit note, not an invoice; merging would lose that distinction.",
        evidenceHash: hash("ce4519aa"),
      },
      {
        documentId: doc(4498),
        rationale: "'#17' used alongside a refund correspondent; semantics differ from '#11'.",
        evidenceHash: hash("ce4498bb"),
      },
    ],
    rationale: "A small but consistent subset uses '#17' with distinct semantics; merge risks data loss.",
    evidenceFingerprint: hash("ev17ev17"),
    createdAt: "2026-07-22T09:03:00Z",
  },
  {
    evidenceId: "evidence_curator40",
    epochId: "cat_epoch_7Ab3cD",
    candidateId: "cand_deleteStale",
    reviewer: "taxonomy_curator",
    evidenceDocumentIds: docs([4001]),
    inspectedDocuments: 12,
    totalDocuments: 12,
    coverage: 1,
    xReceiptCount: 0,
    yReceiptCount: null,
    xReceiptHash: hash("40cc40cc"),
    yReceiptHash: null,
    verdict: "support",
    dissent: null,
    counterexamples: [],
    rationale: "Every historical reference to '#40' has been retagged; the tag is orphaned.",
    evidenceFingerprint: hash("ev40ev40"),
    createdAt: "2026-07-22T08:55:00Z",
  },
  {
    evidenceId: "evidence_auditor40",
    epochId: "cat_epoch_7Ab3cD",
    candidateId: "cand_deleteStale",
    reviewer: "document_evidence_auditor",
    evidenceDocumentIds: docs([4001, 3990]),
    inspectedDocuments: 12,
    totalDocuments: 12,
    coverage: 1,
    xReceiptCount: 0,
    yReceiptCount: null,
    xReceiptHash: hash("40cc40cc"),
    yReceiptHash: null,
    verdict: "support",
    dissent: null,
    counterexamples: [],
    rationale: "Receipt count is zero and no active document carries '#40'; safe to delete.",
    evidenceFingerprint: hash("ev40ev40"),
    createdAt: "2026-07-22T08:59:00Z",
  },
  {
    evidenceId: "evidence_hunter40",
    epochId: "cat_epoch_7Ab3cD",
    candidateId: "cand_deleteStale",
    reviewer: "counterexample_hunter",
    evidenceDocumentIds: docs([3975]),
    inspectedDocuments: 12,
    totalDocuments: 12,
    coverage: 1,
    xReceiptCount: 0,
    yReceiptCount: null,
    xReceiptHash: hash("40cc40cc"),
    yReceiptHash: null,
    verdict: "support",
    dissent: null,
    counterexamples: [],
    rationale: "No counterexample found — the tag is a 2019 import artifact with no live usage.",
    evidenceFingerprint: hash("ev40ev40"),
    createdAt: "2026-07-22T09:02:00Z",
  },
  {
    evidenceId: "evidence_curator12",
    epochId: "cat_epoch_7Ab3cD",
    candidateId: "cand_renameUtilities",
    reviewer: "taxonomy_curator",
    evidenceDocumentIds: docs([5120, 5088]),
    inspectedDocuments: 30,
    totalDocuments: 341,
    coverage: 0.088,
    xReceiptCount: 341,
    yReceiptCount: null,
    xReceiptHash: hash("12dd12dd"),
    yReceiptHash: null,
    verdict: "support",
    dissent: null,
    counterexamples: [],
    rationale: "Singular 'Utility' matches the correspondent naming scheme; a rename preserves all receipts.",
    evidenceFingerprint: hash("ev12ev12"),
    createdAt: "2026-07-22T08:56:00Z",
  },
  {
    evidenceId: "evidence_auditor12",
    epochId: "cat_epoch_7Ab3cD",
    candidateId: "cand_renameUtilities",
    reviewer: "document_evidence_auditor",
    evidenceDocumentIds: docs([5120, 5044]),
    inspectedDocuments: 30,
    totalDocuments: 341,
    coverage: 0.088,
    xReceiptCount: 341,
    yReceiptCount: null,
    xReceiptHash: hash("12dd12dd"),
    yReceiptHash: null,
    verdict: "support",
    dissent: null,
    counterexamples: [],
    rationale: "A rename does not remap any document tags, so all 341 receipts are retained.",
    evidenceFingerprint: hash("ev12ev12"),
    createdAt: "2026-07-22T09:00:00Z",
  },
  {
    evidenceId: "evidence_hunter12",
    epochId: "cat_epoch_7Ab3cD",
    candidateId: "cand_renameUtilities",
    reviewer: "counterexample_hunter",
    evidenceDocumentIds: docs([5044]),
    inspectedDocuments: 30,
    totalDocuments: 341,
    coverage: 0.088,
    xReceiptCount: 341,
    yReceiptCount: null,
    xReceiptHash: hash("12dd12dd"),
    yReceiptHash: null,
    verdict: "support",
    dissent: null,
    counterexamples: [],
    rationale: "No document relies on the plural spelling; the rename introduces no ambiguity.",
    evidenceFingerprint: hash("ev12ev12"),
    createdAt: "2026-07-22T09:04:00Z",
  },
];

// --- proposals (catalog_proposal_projection.v2) -------------------------------
export const catalogProposals: readonly CatalogProposalContract[] = [
  {
    projectionVersion: "catalog_proposal_projection.v2",
    proposalId: "prop_mergeInvoice",
    epochId: "cat_epoch_7Ab3cD",
    kind: "tag",
    intendedAction: "merge",
    xEntityId: 17,
    yEntityId: 11,
    currentEntities: {
      x: { entityId: 17, kind: "tag", name: "Invoices" },
      y: { entityId: 11, kind: "tag", name: "Invoice" },
    },
    proposedValue: "Invoice",
    candidateIds: ["cand_mergeInvoice"],
    evidence: {
      availability: "available",
      evidenceDocumentIds: docs([4821, 4790, 4771, 4762, 4755, 4519, 4498]),
      chair: {
        availability: "decision_recorded",
        verdict: "needs_human",
        action: "request_review",
        sourceEntityId: 17,
        targetEntityId: 11,
        rationale:
          "Two reviewers support the merge but the counterexample hunter found a credit-note subtype; a human should decide whether to split it out first.",
        dissent:
          "Counterexample hunter opposes: '#17' encodes a credit-note distinction in a minority of documents.",
        evidenceIds: ["evidence_curator01", "evidence_auditor01", "evidence_hunter01"],
        confidence: 0.66,
        proposalFingerprint: hash("pr17pr17"),
        evidenceFingerprint: hash("ev17ev17"),
        coverageHash: hash("cov17cov"),
        coverageCount: 7,
        inspectedDocumentCount: 130,
        totalDocumentCount: 214,
        decidedAt: "2026-07-22T09:05:00Z",
      },
    },
    expectedProposalFingerprint: hash("pr17pr17"),
    expectedEvidenceFingerprint: hash("ev17ev17"),
    proposalHash: hash("h017h017"),
    preconditions: [
      { kind: "catalog_epoch", digest: hash("ca7a1091") },
      { kind: "council_evidence", digest: hash("ev17ev17") },
    ],
    freshness: {
      status: "fresh",
      stale: false,
      currentMissing: false,
      expectedPreconditions: [{ kind: "catalog_epoch", digest: hash("ca7a1091") }],
      currentPreconditions: [{ kind: "catalog_epoch", digest: hash("ca7a1091") }],
    },
    decision: { status: "undecided", outcome: null, decidedAt: null },
    apply: { status: "not_started", latestJournalId: null, stepCount: 0, updatedAt: null },
    rationale:
      "Merge 'Invoices' (#17) into 'Invoice' (#11): synonymous names, overlapping usage; held for human decision due to a credit-note counterexample.",
    createdAt: "2026-07-22T09:05:00Z",
  },
  {
    projectionVersion: "catalog_proposal_projection.v2",
    proposalId: "prop_deleteStale",
    epochId: "cat_epoch_7Ab3cD",
    kind: "tag",
    intendedAction: "delete",
    xEntityId: 40,
    yEntityId: null,
    currentEntities: {
      x: { entityId: 40, kind: "tag", name: "Zzz-import-2019" },
      y: null,
    },
    proposedValue: null,
    candidateIds: ["cand_deleteStale"],
    evidence: {
      availability: "available",
      evidenceDocumentIds: docs([4001, 3990, 3975]),
      chair: {
        availability: "decision_recorded",
        verdict: "approve",
        action: "approve",
        sourceEntityId: 40,
        targetEntityId: null,
        rationale: "Unanimous support; the tag has zero active receipts and no counterexamples were found.",
        dissent: null,
        evidenceIds: ["evidence_curator40", "evidence_auditor40", "evidence_hunter40"],
        confidence: 0.98,
        proposalFingerprint: hash("pr40pr40"),
        evidenceFingerprint: hash("ev40ev40"),
        coverageHash: hash("cov40cov"),
        coverageCount: 3,
        inspectedDocumentCount: 12,
        totalDocumentCount: 12,
        decidedAt: "2026-07-22T09:06:00Z",
      },
    },
    expectedProposalFingerprint: hash("pr40pr40"),
    expectedEvidenceFingerprint: hash("ev40ev40"),
    proposalHash: hash("h040h040"),
    preconditions: [
      { kind: "catalog_epoch", digest: hash("ca7a1091") },
      { kind: "council_evidence", digest: hash("ev40ev40") },
    ],
    freshness: {
      status: "fresh",
      stale: false,
      currentMissing: false,
      expectedPreconditions: [{ kind: "catalog_epoch", digest: hash("ca7a1091") }],
      currentPreconditions: [{ kind: "catalog_epoch", digest: hash("ca7a1091") }],
    },
    decision: { status: "approved", outcome: "approved", decidedAt: "2026-07-22T09:30:00Z" },
    apply: { status: "not_started", latestJournalId: null, stepCount: 0, updatedAt: null },
    rationale: "Delete stale tag 'Zzz-import-2019' (#40) with zero active receipts.",
    createdAt: "2026-07-22T09:06:00Z",
  },
  {
    projectionVersion: "catalog_proposal_projection.v2",
    proposalId: "prop_renameUtilities",
    epochId: "cat_epoch_7Ab3cD",
    kind: "tag",
    intendedAction: "rename",
    xEntityId: 12,
    yEntityId: null,
    currentEntities: {
      x: { entityId: 12, kind: "tag", name: "Utilities" },
      y: null,
    },
    proposedValue: "Utility",
    candidateIds: ["cand_renameUtilities"],
    evidence: {
      availability: "available",
      evidenceDocumentIds: docs([5120, 5088, 5044]),
      chair: {
        availability: "decision_recorded",
        verdict: "approve",
        action: "approve",
        sourceEntityId: 12,
        targetEntityId: null,
        rationale: "Unanimous support for the singular form; no document semantics change on a rename.",
        dissent: null,
        evidenceIds: ["evidence_curator12", "evidence_auditor12", "evidence_hunter12"],
        confidence: 0.95,
        proposalFingerprint: hash("pr12pr12"),
        evidenceFingerprint: hash("ev12ev12"),
        coverageHash: hash("cov12cov"),
        coverageCount: 3,
        inspectedDocumentCount: 90,
        totalDocumentCount: 341,
        decidedAt: "2026-07-22T09:07:00Z",
      },
    },
    expectedProposalFingerprint: hash("pr12pr12"),
    expectedEvidenceFingerprint: hash("ev12ev12"),
    proposalHash: hash("h012h012"),
    preconditions: [
      { kind: "catalog_epoch", digest: hash("ca7a1091") },
      { kind: "council_evidence", digest: hash("ev12ev12") },
    ],
    freshness: {
      status: "stale",
      stale: true,
      currentMissing: false,
      expectedPreconditions: [{ kind: "catalog_epoch", digest: hash("ca7a1091") }],
      currentPreconditions: [{ kind: "catalog_epoch", digest: hash("ca7d4094") }],
    },
    decision: { status: "approved", outcome: "approved", decidedAt: "2026-07-22T09:31:00Z" },
    apply: { status: "not_started", latestJournalId: null, stepCount: 0, updatedAt: null },
    rationale:
      "Rename 'Utilities' (#12) to 'Utility'; approved, but the catalog changed since — recompute before applying.",
    createdAt: "2026-07-22T09:07:00Z",
  },
];
